column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 3
quote_style = "AutoPreferDouble"
call_parentheses = "None"
collapse_simple_statement = "Always"

[sort_requires]
enabled = false